name: Replace README

on:
  workflow_dispatch:
    inputs:
      repo:
        default: 'MarineHakobyan/MarineHakobyan'
      branch:
        default: 'main'

jobs:
  replace-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run replace_readme.sh
      run: |
        chmod +x replace_readme.sh
        ./replace_readme.sh
