name: Update README

on:
  # Run the workflow on push events to the main branch
  push:
    branches:
      - main

  # Run automatically every 24 hours (1 hour after UTC Midnight)
  schedule:
    - cron: "0 1 * * *"

  # Allows to manually run the job at any time
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      - name: Run script to update README
        run: |
          ls -la
          git branch --sh
          bash update_readme.sh
        shell: bash

      - name: Display README content
        run: git status

      - name: Git configuration
        run: |
          git config --local user.email "marine.hakobyan4649.com"
          git config --local user.name "MarineHakobyan"

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Update README on schedule"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
