name: Update README on Schedule

on:
  # Run the workflow at 01:00 on the first day of every month (adjust cron syntax as needed)
  schedule:
    - cron: "0 1 */1 * *"

      
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - name: Run script to update README
        run: bash your-script.sh  # Replace with your actual script name

      - name: Install required dependencies (if needed)
        # Add this step if your script requires specific tools
        run: |
          sudo apt update  # Update package lists (adjust as needed)
          sudo apt install some-package  # Install a specific package (adjust as needed)

      - name: Commit changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md  # Add the updated README file
          git commit -m "Update README on schedule"
      - name: Create a pull request
        uses: apps/auto-pull-request@v2  # Use a dedicated action for pull requests
        with:
          title: "Automatic Update: Updated README"
          body: "This pull request automatically updates the README file based on your script."
          head: ${{ github.sha }}  # Current commit SHA as the pull request head
          base: main  # Target branch for the pull request
