name: Update Readme

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 1 */1 * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch (or update for your actual target branch)
  push:
    branches:
    - master  # Update if your target branch is different

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Check script permissions (assuming script is in repository root)
      - name: Check replace_readme.sh permissions
        run: chmod +x replace_readme.sh
      
      # Run the ./replace_readme.sh script with verbose output
      - name: Run replace_readme.sh (with verbose output)
        run: ./replace_readme.sh --verbose
        with:
          target_branch: main  # Update if your target branch is different
          build_dir: dist     # Update if your build directory is different
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (Optional) Install dependencies if needed (replace with actual commands)
      - name: Install dependencies (if required)
        run: |
          sudo apt-get update
          sudo apt-get install -y <package_name>  # Replace with actual package

